### PR TITLE
add env also to tideways hostname

### PR DESCRIPTION
**Pull request by rwos**
makes it easier to see where the stuff is from on tideways.io

### CODE REVIEW

**Comment by rwos** [comment]
hm, build fails with
```
ERROR: unsatisfiable constraints:

  nodejs-6.10.0-r0:

    breaks: world[nodejs=6.9.5-r0]
```

I don't think this has something to do with my change... 😬

**Comment by till** [comment]
@rwos yeah, this is why one wants to split up images, so you have individual layers. So each time we rebuild this image for whatever reason, we have to check dependencies. This is not ideal yet.

Can you update the nodejs version:
https://pkgs.alpinelinux.org/packages?name=nodejs&branch=&repo=&arch=&maintainer=

**Comment by gilleyj** [comment]
@rwos let me see what I can do to fix this sorry I missed these notifications

**Comment by rwos** [comment]
@gilleyj yay, thanks!

**Comment by gilleyj** [comment]
I'll go ahead and merge/close and deploy a new tag to docker-hub you can use this now with wpt-backend:latest

**Pull request merged**
